version: '3.7'

services:

  druid-postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid

  # Need 3.5 or later for container nodes
  druid-zookeeper:
    container_name: zookeeper
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1

  druid-coordinator:
    image: apache/druid:0.22.1
    container_name: coordinator
    depends_on:
      - druid-zookeeper
      - druid-postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - environment

  druid-broker:
    image: apache/druid:0.22.1
    container_name: broker
    depends_on:
      - druid-zookeeper
      - druid-postgres
      - druid-coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - environment

  druid-historical:
    image: apache/druid:0.22.1
    container_name: historical
    depends_on:
      - druid-zookeeper
      - druid-postgres
      - druid-coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - environment

  druid-middlemanager:
    image: apache/druid:0.22.1
    container_name: middlemanager
    depends_on:
      - druid-zookeeper
      - druid-postgres
      - druid-coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - environment

  druid-router:
    image: apache/druid:0.22.1
    container_name: router
    depends_on:
      - druid-zookeeper
      - druid-postgres
      - druid-coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - environment
